# title of website
title: webstack

# description of website
description: luckyhakcing's navigation site

# favicon of website
favicon: "https://webstack.cc/assets/images/favicon.png"

# your website url
url: https://ws.wrss.top

# github profile url
github: "https://github.com/toolsz/webstack"

# footer message
footer: © 2021-2021 @luckyhacking

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
# google_analytics: "G-EXE1PJ8CR2"

content:
  categories:
    - name: 在线IDE
      sites:
        - name: 在线golang
          description: 有代码提示, 比golang官方的playground好用
          url: https://goplay.tools/
        - name: 在线PHP
          url: https://3v4l.org/
        - name: Replit
          description: 在线使用的通用IDE, 支持所有主流语言, 但是需要登录, 比较麻烦
          url: https://replit.com/
        - name: Colaboratory
          description: 在线使用的Jupyter notebook环境, 机器学习必备
          url: https://colab.research.google.com/
        - name: Compiler Explorer
          description: 在线C++编译器能够查看c++/rust/golang编译过程的在线编译器
          url: https://godbolt.org/
    - name: 开发工具
      sites:
        - name: Pagespeed Insights
          description: 页面性能分析工具，很好用
          url: https://pagespeed.web.dev/
        - name: deps.dev
          description: 用来查看开源项目的依赖是否有漏洞
          url: https://deps.dev/
        - name: Staticfile CDN
          description: 收录知名开源js、css等静态资源的网站
          url: https://www.staticfile.org/
        - name: 网易DNS检测工具
          description: 
          url: http://nstool.netease.com/
        - name: CSVJSON
          description: 用来csv和json之间互转, 以及json美化和json检验
          url: https://csvjson.com/
        - name: JSON Editor Online
          description: JSON 工具，可以对比两个 JSON，以及分享 JSON 片段
          url: https://jsoneditoronline.org/
        - name: Diffchecker
          description: diff 工具，diff 文本、diff 图片、diff PDF
          url: https://www.diffchecker.com/diff
        - name: misaka ping
          description:
          url: https://ping.sx/ping
    - name: golang开发工具
      sites:
        - name: sql-to-struct
          description: 在线sql转struct
          url: http://sql2struct.atotoa.com/
        - name: curl-to-go
          description: curl-to-go
          url: https://mholt.github.io/curl-to-go/
        - name: JSON-to-GO
          description:
          url: https://mholt.github.io/json-to-go/
        - name: YAML-to-go
          description: YAML-to-Go
          url: https://zhwt.github.io/yaml-to-go/
        - name: TOML-to-go
          description: 
          url: https://xuri.me/toml-to-go/
        - name: json-to-struct
          url: http://www.hailaz.cn/static/pages/tools/tools.html
        - name: JSON转Struct
          url: https://www.printlove.cn/tools/json2go/
    - name: 云服务
      sites:
        - name: 云片
          url: https://www.yunpian.com/
        - name: 聚合数据
          url: https://www.juhe.cn/
        - name: nowapi
          description: 常用api服务,还有余额
          url: https://www.nowapi.com/
        - name: 百度智能云
          description: 百度智能云,用过车牌识别之类的服务
          url: https://cloud.baidu.com/
        - name: 高德开放平台
          description: 地图服务
          url: https://lbs.amap.com/
        - name: 超级鹰
          description: 打码平台,还不错
          url: https://www.chaojiying.com/
        - name: 腾讯防水墙
          description: 验证码/内容平台防垃圾内容等服务
          url: https://007.qq.com/
        - name: 芝麻HTTP
          descriptin: 比较好用的代理IP网站, 但是不便宜, 用过几次还可以
          url: https://h.zhimaruanjian.com/
    - name: 正则
      sites:
        - name: regex101
          description: 正则在线调试网站，非常好用
          url: https://regex101.com/
        - name: 正则大全any-rule
          description: 收录了常用业务的正则
          url: https://any86.github.io/any-rule/
        - name: 图解正则Regexper
          description: 图解正则
          url: https://regexper.com/
    - name: 日常服务
      sites:
        - name: Markmap
          description: 在线markdown转思维导图
          url: https://markmap.js.org/repl
        - name: Mermaid Live Editor
          description: 在线mermaid编辑器
          url: https://mermaid.live/edit/
        - name: Excalidraw
          description: 流程图工具，可以画手写风格的图表
          url: https://excalidraw.com/
        - name: 逮蝦戶
          description: spotify之类境外服务的拼车网站
          url: https://daixiahu.co/#/buses
        - name: xclient
          description: mac的破解软件
          url: https://xclient.info/
        - name: CloudConvert
          description: 在线文件转换网站，所有格式应有尽有
          url: https://cloudconvert.com/
        - name: 云短信
          description: 在线短信接收平台,用来注册临时使用(只使用一次)的网站
          url: https://yunduanxin.net/
        - name: iLovePDF
          description: 提供所有PDF相关的在线服务
          url: https://www.ilovepdf.com/
        - name: 白描OCR
          description: 白描OCR的在线服务
          url: https://web.baimiaoapp.com/
        - name: StackEdit
          description: 在线markdown工具，其实没啥用
          url: https://stackedit.io/
        - name: TinyPNG
          description: 在线图片压缩服务
          url: https://tinypng.com/
        - name: IPLC
          description: 翻墙工具
          url: https://portal.uuks.club/
#         - name: IconFont
#           description: 阿里巴巴矢量图标库
#           url: http://www.iconfont.cn/
        - name: EasyIcon
          description: PNG、ICO、ICNS格式图标搜索、图标下载服务
          url: http://www.easyicon.cc/
        - name: FlatIcon
          description: 类似EasyIcon, 可以直接搜索icon
          url: https://www.flaticon.com/
#         - name: 稿定抠图
#           description: 免费在线抠图软件,图片快速换背景-抠白底图
#           url: https://www.gaoding.com
        - name: 草料二维码
          description: 
          url: https://cli.im/
        - name: Blogtrottr
          description: 订阅rss, 发送到邮箱(ttrss也支持发送某个feed到邮箱的功能)
          url: https://blogtrottr.com/
        - name: 蜜蜂剪辑
          description: 蜜蜂剪辑，在线音视频处理
          url: https://beecut.cn/
        - name: Zamzar
          description:  视频/音频/图片/电子书转换器, 非常强大的在线工具
          url: https://www.zamzar.com/
    - name: 投资
      sites:
        - name: Investment Calculator
          description: 计算投资收益什么的，好用
          url: https://www.calculator.net/investment-calculator.html
        - name: 烯牛数据
          description: 免费的投创数据平台，其他类似的都要收费
          url: https://www.xiniudata.com/
        - name: Neat Reader
          description: 在线阅读ePUB/mobi等格式文件, 阅读体验不错, 不再需要下载calibre之类的本地阅读器
          url: https://www.neat-reader.cn/
    - name: 综合在线工具
      sites:
        - name: OKTools
          url: https://oktools.net/number
        - name: transform
          description: 各种文件格式转换
          url: https://transform.tools/
        - name: verytoolz
          description: 各种文件格式转换
          url: https://verytoolz.com/yaml-parser.html

