# title of website
title: webstack

# description of website
description: hapihacking's navigation site

# favicon of website
favicon: "https://webstack.cc/assets/images/favicon.png"

# your website url
url: https://ws.wrss.top

# github profile url
github: "https://github.com/toolsz/webstack"

# footer message
footer: © 2021-2021 @hapihacking

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google Analytics
# google_analytics: "G-EXE1PJ8CR2"

content:
  categories:
    - name: cy
      sites:
        - name: 阿里云
          url: https://home.console.aliyun.com/home/dashboard/ProductAndService
          icon: https://jeffcott.oss-cn-beijing.aliyuncs.com/images/ops/aliyun.jpg
        - name: spotify
          url: https://open.spotify.com/
        - name: Google翻译
          url: https://translate.google.cn/?sl=auto&tl=en&op=translate
        - name: Google Drive
          url: https://drive.google.com/drive/my-drive
        - name: 微软邮箱Outlook
          url: https://outlook.live.com/
        - name: Notion
          url: https://www.notion.so/
        - name: 高驰Training Hub
          url: https://t.coros.com/admin/views/dash-board
        - name: The Weather Channel # 比墨迹天气好用
          url: https://weather.com/zh-CN/weather/hourbyhour/l/7f14186934f484d567841e8646abc61b81cce4d88470d519beeb5e115c9b425a
        - name: QWeather - 和风天气
          url: https://www.qweather.com/pcpn/jiading-101020500.html
        - name: Weather Spark # 全年气候和平均天气
          url: https://zh.weatherspark.com/y/137446/%E4%B8%AD%E5%9B%BD%E3%80%81%E4%B8%8A%E6%B5%B7%E5%B8%82%E7%9A%84%E5%85%A8%E5%B9%B4%E5%B9%B3%E5%9D%87%E5%A4%A9%E6%B0%94
    - name: tools
      sites:
        - name: Programiz 通用IDE
          description: 通用IDE，相比于Repl.it响应更快，使用更方便（当然功能上不如Repl强大，没有代码提示什么的）
          url: https://www.programiz.com/golang/online-compiler/
        - name: Colaboratory IDE
          description: 在线使用的Jupyter notebook环境，机器学习必备
          url: https://colab.research.google.com/
        - name: Compiler Explorer IDE
          description: 在线C++编译器能够查看c++/rust/golang编译过程的在线编译器
          url: https://godbolt.org/
        - name: AST explorer IDE
          description: 一款用于探索各种代码解析器生成的抽象语法树 (Abstract Syntax Tree, AST) 的在线工具
          url: https://astexplorer.net/
        - name: Staticfile CDN
          description: 收录知名开源js、css等静态资源的网站
          url: https://www.staticfile.org/
        - name: 阿里云镜像源
          url: https://developer.aliyun.com/mirror/
          icon: https://jeffcott.oss-cn-beijing.aliyuncs.com/images/ops/aliyun.jpg
        - name: 中科大镜像源
          url: https://mirrors.ustc.edu.cn/
        - name: 数据结构模拟 Data Structure Visualizations
          description: 各种数据结构的动画
          url: https://www.cs.usfca.edu/~galles/visualization/Algorithms.html
        - name: httpbin
          description: 用来通过查看url请求是否符合预期，来看代码是否有问题，或者当前网络环境（比如容器内）是否有问题
          url: http://httpbin.org/
        - name: CodeCov
          url: https://about.codecov.io/
        - name: Coveralls
          url: https://coveralls.io/
        - name: Explainshell
          url: https://explainshell.com/
        - name: TOML-to-Go
          url: https://xuri.me/toml-to-go/
          description: Convert TOML to Go instantly
        - name: YAML-to-Go
          url: https://zhwt.github.io/yaml-to-go/
          description: Convert YAML to Go struct
        - name: JSON-to-Go
          url: https://mholt.github.io/json-to-go/
          description: Convert JSON to Go instantly
        - name: golang在线工具
          url: https://www.printlove.cn/tools/yaml2go
          description: json转go结构体，yaml转go结构体，XML转json，sql转gozero/GORM/ES/entgo/MongoDB
        - name: golang在线工具集
          url: http://www.gotool.top/handlesql/sql2proto
          description: sql处理、json处理
        - name: sql2dsl
          url: http://sql2dsl.atotoa.com/
          description: sql转struct和sql转ES
        - name: soJSON
          url: https://www.sojson.com/jshtml.html
          description: js/css 格式化/压缩/解压缩/美化
        - name: Online YAML Tools
          url: https://onlineyamltools.com/
          description: Simple, free and easy to use YAML utilities
        - name: Online JSON Tools
          url: https://onlinejsontools.com/
          description: Simple, free and easy to use JSON utilities
        - name: Transform
          url: https://transform.tools/
          description: JSON、yaml、toml之类的数据转换
        - name: resource-hint-validator
          description: 一款检查preload, prefetch, preconnect等Resource Hints使用是否恰当的工具
          url: https://www.debugbear.com/resource-hint-validator

        - name: itdog
          url: https://www.itdog.cn/
        - name: 网易DNS检测工具
          url: http://nstool.netease.com/
        - name: misaka ping
          url: https://ping.sx/ping
          icon: https://ping.sx/favicon.ico
        - name: DNSdumpster
          description: 查看某个域名下的所有二级域名
          url: https://dnsdumpster.com/
        - name: regex101
          description: 正则在线调试网站，非常好用
          url: https://regex101.com/
        - name: 图解正则regex-vis
          description: 比Regexper好用
          url: https://regex-vis.com/
        - name: Diff Checker
          url: https://www.diffchecker.com/zh-Hans/
        - name: Docker Hub
          url: https://hub.docker.com/search?q=
        - name: Docker文档
          url: https://docs.docker.com/reference/
    - name: doc
      sites:
        - name: Quick Reference
          url: https://quickref.pipecraft.net/
        - name: alpine-packages
          url: https://pkgs.alpinelinux.org/packages

        - name: apifox
          description: apifox提供的api开放平台，提供了基本上所有主流服务的文档和调试，用起来很方便
          url: https://www.apifox.cn/apihub/
        - name: 云片
          url: https://www.yunpian.com/
        - name: 聚合数据
          description: 比nowapi好用
          url: https://www.juhe.cn/
        - name: 百度智能云
          description: 百度智能云，用过车牌识别之类的服务
          url: https://cloud.baidu.com/
        - name: 高德开放平台
          url: https://lbs.amap.com/

        - name: 腾讯防水墙
          description: 验证码/内容平台防垃圾内容等服务
          url: https://007.qq.com/

        - name: gozero文档
          url: https://go-zero.dev/cn/docs/introduction/
        - name: Goland文档
          description: IDE相关问题别再乱查各种帖子了，直接看文档最好
          url: https://www.jetbrains.com/help/go/meet-the-product.html
        - name: GORM文档
          url: https://gorm.io/zh_CN/docs/index.html
        - name: casbin文档
          url: https://casbin.org/zh/docs/overview

        - name: UmiJS文档
          url: https://umijs.org/zh-CN/docs/load-on-demand
        - name: Element文档
          description: ⚠️注意版本
          url: https://element.faas.ele.me/2.14/#/zh-CN/component/layout
        - name: Element Plus文档
          url: https://element-plus.gitee.io/zh-CN/component/button.html
        - name: k8s文档
          url: https://kubernetes.io/zh/docs/reference/
        - name: kubesphere
          url: https://kubesphere.io/zh/
        - name: Artifact Hub
          url: https://artifacthub.io/packages/search?sort=relevance&page=1
        - name: Helm
          url: https://helm.sh/zh/docs/intro/quickstart/
        - name: 云原生资料库
          description: k8s/Istio/Envoy教程
          url: https://lib.jimmysong.io/kubernetes-handbook/
        - name: Prometheus文档
          url: https://prometheus.io/docs/prometheus/latest/getting_started/
        - name: Redis命令/文档
          description: 主要用来查命令（当然，还有文档）
          url: https://redis.io/commands/
        - name: Gitea文档
          url: https://docs.gitea.io/zh-cn/
        - name: Ansible文档
          description: 找了几个中文版文档，版本都很老（将就看英文版吧）
          url: https://docs.ansible.com/ansible/latest/index.html
        - name: Ansible Galaxy
          url: https://galaxy.ansible.com/home 
        - name: gh-actions集合
          url: https://github.com/marketplace?type=actions
        - name: gh-actions官方文档
          url: https://docs.github.com/cn/actions/quickstart
        - name: gitlab官方文档
          url: https://docs.gitlab.com/ee/
        - name: ElasticSearch文档（ES）
          url: https://www.elastic.co/guide/en/elasticsearch/reference/master/release-highlights.html
        - name: gh文档
          url: https://docs.github.com/zh
        - name: MongoDB文档
          url: https://docs.mongoing.com/

    - name: rc
      sites:
        - name: 油猴脚本Greasy Fork
          url: https://greasyfork.org/zh-CN
        - name: Table Convert
          url: https://tableconvert.com/
          icon: https://tableconvert.com/images/favicon.png

        - name: ChartCube
          description: 相当于可以在线使用的echarts，可以导出饼图柱状图折线图等，但仅支持导入csv/excel/json数据
          url: https://chartcube.alipay.com/upload
        - name: EasyIcon
          description: 比FlatIcon、IconFont好用
          url: http://www.easyicon.cc/
        - name: Investment Calculator
          description: 计算投资收益什么的，好用
          url: https://www.calculator.net/investment-calculator.html
        - name: Koodo Reader
          description: 比neat-reader好用
          url: https://reader.960960.xyz/
        - name: 冷熊简历
          description: 木及简历
          url: https://cv.ftqq.com/#
          icon: https://fox.ftqq.com/bearcv/favicon.png
        - name: readme.so
          description: 辅助写README的工具，还不错
          url: https://readme.so/editor
          icon: https://readme.so/favicon.ico
        - name: 白描OCR
          description: 白描OCR的在线服务
          url: https://web.baimiaoapp.com/

        - name: Temp Mail - 临时性匿名邮箱
          url: https://temp-mail.org/zh
        - name: 云短信 - 临时性匿名短信
          description: 在线短信接收平台，用来注册临时使用(只使用一次)的网站
          url: https://yunduanxin.net/        

        - name: CloudConvert
          description: 几乎所有文件格式的转换工具
          url: https://cloudconvert.com/
        - name: Zamzar - File Conversion progress
          description: Convert documents, images, videos & sound - 1100+ formats supported
          url: https://www.zamzar.com/
        - name: iLovePDF
          url: https://www.ilovepdf.com/
        - name: IPLC
          url: https://iplc.vip
        - name: 白板工具OneModel
          description: 适合用来画架构图
          url: https://www.onemodel.app/
    - name: cc
      sites:
        - name: IT桔子
          url: https://www.itjuzi.com
        - name: Wiki How
          url: https://zh.wikihow.com/%E9%A6%96%E9%A1%B5
        - name: 烯牛数据
          description: 免费的投创数据平台，其他类似的都要收费
          url: https://www.xiniudata.com/
          icon: https://www.xiniudata.com/static/image/icons/xiniu-icon-apple-touch.png
        - name: Kaggle
          url: https://www.kaggle.com/
        - name: JoinQuant聚宽量化交易平台
          url: https://www.joinquant.com/
        - name: 飞浆AI Studio
          url: https://aistudio.baidu.com
        - name: 七麦数据
          url: https://www.qimai.cn/
        - name: 国标/行标
          description: 查看全文，自带搜索功能，输入关键字或者国标编号即可
          url: http://openstd.samr.gov.cn/bzgk/gb/std_list
        - name: 程序员在囧途codersway
          url: https://www.jtthink.com/
        - name: RSSHub文档
          url: https://docs.rsshub.app/social-media.html#bilibili
          icon: https://docs.rsshub.app/logo.png
        - name: COKEMV
          url: https://cokemv.me/
        - name: tg
          url: https://web.telegram.im/
        - name: Qwerty Learner
          url: https://kaiyiwing.github.io/qwerty-learner/
        - name: Go夜读 TalkGo 
          url: https://talkgo.org/
        - name: Supjav
          url: https://supjav.com/
        - name: 黑猫投诉
          url: https://tousu.sina.com.cn/
        - name: PACK HACKER
          url: https://packhacker.com/
        - name: gofun
          url: https://1005281342.gitbook.io/gofun/go-xie-cheng/goroutine
        - name: Go 语言设计与实现
          url: https://draveness.me/golang/
        - name: K8S训练营
          url: https://www.qikqiak.com/k8strain/
        - name: Linux kernel脉络和主干总结
          url: https://www.kancloud.cn/zhangyi8928/kernel/531187
        - name: go-interview
          url: https://www.yuque.com/go-interview/set/qhe51m
        - name: BlackGlory
          url: https://blackglory.me/
        - name: CloudWeGo字节博客
          url: https://www.cloudwego.io/zh/blog/
        - name: LeetCode
          url: https://leetcode-cn.com/
        - name: CodeTop企业题库
          url: https://codetop.cc/home
        - name: LintCode炼码
          url: https://www.lintcode.com/problem/
        - name: LeetCode Cookbook
          url: https://books.halfrost.com/leetcode/
        - name: 算法珠玑 algo
          url: https://algorithm-essentials.soulmachine.me/
        - name: labuladong 的算法小抄 algo
          url: https://labuladong.github.io/algo/
        - name: algorithm-pattern
          url: https://greyireland.gitbook.io/algorithm-pattern/
        - name: Awesome List
          url: https://asmen.icopy.site/awesome/awesome-linux/
        - name: deps.dev
          description: 用来查看开源项目的依赖是否有漏洞
          url: https://deps.dev/
        - name: Github OSS Insight
          description: 查看gh某个repo的star（`starchart.cc`）/PR/issue等等数据，以及比较repo（类似`Github Compare`）
          url: https://ossinsight.io/
        - name: OSSRank
          url: https://ossrank.com/fast
        - name: OpenSource Builders
          description: 一些服务的开源替代品，还不错
          url: https://opensource.builders/
        - name: AlternativeTo - Crowdsourced software recommendations
          url: https://alternativeto.net/
        - name: MacScripter - macOS and iOS automation
          url: https://www.macscripter.net/
        - name: Tiny Tiny RSS - Community
          url: https://community.tt-rss.org/
        - name: Hugging Face
          description: The AI community building the future.
          url: https://huggingface.co/
        - name: ChatGPT Shortcut
          description: 简单易用的 ChatGPT 快捷指令表，让生产力倍增！标签筛选、关键词搜索和一键复制 Prompts | Tag filtering, keyword search, and one-click copy prompts
          url: https://www.aishort.top/
        - name: Regex.ai
          description: Artificial Intelligence Regular Expression Generator
          url: https://regex.ai/
        - name: Open Prompt - ChatGPT
          url: https://openprompt.co/
        - name: nGQL GPT Composer
          url: https://ngql-gpt.siwei.io/
        - name: OPS 提示词工作室
          description: 可视化编辑提示词 | 一键翻译 AIGC 提示词 | Midjourney 提示词 | OpenPromptStudio made by Moonvy 月维
          url: https://moonvy.com/apps/ops/
        - name: 猿人学Web端爬虫攻防刷题平台-题目列表
          url: https://match.yuanrenxue.cn/list
        - name: 竹白专栏检索 - ZhuBai
          url: https://zb.liey.cn/
        - name: Docusaurus - docs
          url: https://docusaurus.io/zh-CN/docs
        - name: World Athletics
          url: https://worldathletics.org/records/all-time-toplists/road-running/marathon/outdoor/men/senior
        - name: 最酷 - zuicool
          description: 比赛报名
          url: https://zuicool.com/events?type=run&where=jiangzhe&regtype=reg
        - name: 深言达意 – WantWords
          description: 反向词典 找词，成语
          url: https://www.shenyandayi.com/
        - name: 捷径社区 - shortcuts
          url: https://sharecuts.cn/
        - name: 捷径库 - shortcuts
          url: https://jiejingku.net/
        - name: RQrun
          url: https://www.rq.run/user
        - name: 天天基金 - ttjj
          url: https://www.1234567.com.cn/
        - name: 飞客 - flyert
          url: https://www.flyert.com/portal.php
        - name: 携程 - ctrip
          url: https://www.ctrip.com/
        - name: 马拉松发烧友 - MarathonFans - 新浪博客
          url: https://blog.sina.com.cn/s/articlelist_2962914900_0_1.html
        - name: RunRepeat
          description: 跑鞋评测
          url: https://runrepeat.com/catalog/running-shoes
        - name: ASMRGAY
          url: https://www.asmrgay.com/











