# title of website
title: webstack

# description of website
description: x1a0xf's navigation site

# favicon of website
# favicon: "https://github.com/x1a0xf.png?size=40"
favicon: "https://webstack.cc/assets/images/favicon.png"

# your website url
url: https://x1a0xf.github.io/webstack/

# github profile url
github: "https://github.com/x1a0xf"

# footer message
footer: © 2021-2021 @x1a0xf

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: false
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 在线IDE
      sites:
        - name: 在线PHP
          url: https://3v4l.org/
        - name: 在线golang
          url: https://goplay.tools/
        - name: Replit
          description: 在线使用的通用IDE,支持所有主流语言,但是需要登录,比较麻烦
          url: https://replit.com/
        - name: Colaboratory
          description: 可以在线使用的Jupyter notebook环境,机器学习必备
          url: https://colab.research.google.com/
        - name: Compiler Explorer
          description: 在线C++编译器能够查看c++/rust/golang编译过程的在线编译器
          url: https://godbolt.org/
    - name: 开发工具
      sites:
        - name: pagespeed insights
          description: 页面性能分析工具，很好用
          url: https://pagespeed.web.dev/
        - name: deps.dev
          description: 用来查看开源项目的依赖是否有漏洞
          url: https://deps.dev/
    - name: 云服务
      sites:
        - name: 云片
          url: https://www.yunpian.com/
        - name: 聚合数据
          url: https://www.juhe.cn/
        - name: nowapi
          description: 常用api服务,还有余额
          url: https://www.nowapi.com/
        - name: 百度智能云
          description: 百度智能云,用过车牌识别之类的服务
          url: https://cloud.baidu.com/
        - name: 高德开放平台
          description: 地图服务
          url: https://lbs.amap.com/
        - name: 超级鹰
          description: 打码平台,还不错
          url: https://www.chaojiying.com/
        - name: 腾讯防水墙
          description: 验证码/内容平台防垃圾内容等服务
          url: https://007.qq.com/
    - name: 正则
      sites:
        - name: regex101
          description: 正则在线调试网站，非常好用
          url: https://regex101.com/
        - name: 正则大全any-rule
          description: 收录了常用业务的正则
          url: https://any86.github.io/any-rule/
        - name: 图解正则Regexper
          description: 图解正则
          url: https://regexper.com/
    - name: 日常服务
      sites:
        - name: markmap
          description: 在线markdown转思维导图
          url: https://markmap.js.org/repl
        - name: mermaid-live-editor
          description: 在线mermaid编辑器
          url: https://mermaid.live/edit/
        - name: 逮蝦戶
          description: spotify之类境外服务的拼车网站
          url: https://daixiahu.co/#/buses
        - name: xclient
          description: mac的破解软件网站
          url: https://xclient.info/
        - name: CloudConvert
          description: 在线文件转换网站，所有格式应有尽有
          url: https://cloudconvert.com/
        - name: 云短信
          description: 在线短信接收平台,用来注册临时使用(只使用一次)的网站
          url: https://yunduanxin.net/
        - name: iLovePDF
          description: 提供所有PDF相关的在线服务
          url: https://www.ilovepdf.com/
        - name: 白描OCR
          description: 白描OCR的在线服务
          url: https://web.baimiaoapp.com/
        - name: StackEdit
          description: 在线markdown工具，其实没啥用
          url: https://stackedit.io/
        - name: TinyPNG
          description: 在线图片压缩服务
          url: https://tinypng.com/
        - name: IPLC.VIP
          description: 翻墙工具
          url: https://portal.uuks.club/
    - name: 常用推荐
      sites:
        - name: Dribbble
          description: 全球UI设计师作品分享平台。
          url: https://dribbble.com/
        - name: Behance
          description: Adobe旗下的设计师交流平台，来自世界各地的设计师在这里分享自己的作品。
          url: https://behance.net/
        - name: UI中国
          description: 图形交互与界面设计交流、作品展示、学习平台。
          url: http://www.ui.cn/
        - name: 站酷
          description: 中国人气设计师互动平台
          url: http://www.zcool.com.cn/
        - name: Pinterest
          description: 全球美图收藏采集站
          url: https://www.pinterest.com/
        - name: 花瓣
          description: 收集灵感,保存有用的素材
          url: http://huaban.com/
        - name: 优设
          description: 设计师交流学习平台
          url: http://www.uisdc.com/
        - name: Producthunt
          description: 发现新鲜有趣的产品
          url: https://www.producthunt.com/
        - name: Youtube
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: Google
          description: 全球最大的UI学习分享平台
          url: https://www.google.com/
        - name: Medium
          description: Read, write and share stories that matter
          url: https://medium.com/

    - name: 发现产品
      sites:
        - name: NEXT
          description: 不错过任何一个新产品
          url: http://next.36kr.com/posts
        - name: 少数派
          description: 高品质数字消费指南
          url: https://sspai.com/
        - name: 利器
          description: 创造者和他们的工具
          url: http://liqi.io/
        - name: Today
          description: 为身边的新产品喝彩
          url: http://today.itjuzi.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/
        - name: Pttrns
          description: Check out the finest collection of design patterns, resources, mobile apps and inspiration
          url: https://www.pttrns.com/
        - name: Collect UI
          description: Daily inspiration collected from daily ui archive and beyond.
          url: http://collectui.com/
        - name: UI uigreat
          description: APP界面截图参考
          url: http://ui.uigreat.com/
        - name: Android Niceties
          description: A collection of screenshots encompassing some of the most beautiful looking Android apps.
          url: http://androidniceties.tumblr.com/
    - name: 网页灵感
      sites:
        - name: Awwwards
          description: Awwwards are the Website Awards that recognize and promote the talent and effort of the best developers, designers and web agencies in the world.
          url: https://www.awwwards.com/
        - name: CSS Design Awards
          description: Website Awards & Inspiration - CSS Gallery
          url: https://www.cssdesignawards.com/
        - name: The FWA
          description: FWA - showcasing innovation every day since 2000
          url: https://thefwa.com/
        - name: Ecommercefolio
          description: Only the Best Ecommerce Design Inspiration
          url: http://www.ecommercefolio.com/
        - name: Lapa
          description: The best landing page design inspiration from around the web.
          url: http://www.lapa.ninja/
        - name: Reeoo
          description: web design inspiration and website gallery
          url: http://reeoo.com/
        - name: Designmunk
          description: Best Homepage Design Inspiration
          url: https://designmunk.com/
        - name: Best Websites Gallery
          description: Website Showcase Inspiration | Best Websites Gallery
          url: https://bestwebsite.gallery/
        - name: Pages
          description: Curated directory of the best Pages
          url: http://www.pages.xyz/
        - name: SiteSee
          description: SiteSee is a curated gallery of beautiful, modern websites collections.
          url: https://sitesee.co/
        - name: Site Inspire
          description: A CSS gallery and showcase of the best web design inspiration.
          url: https://www.siteinspire.com/
        - name: WebInspiration
          description: 网页设计欣赏,全球顶级网页设计
          url: http://web.uedna.com/
        - name: navnav
          description: A ton of CSS, jQuery, and JavaScript responsive navigation examples, demos, and tutorials from all over the web.
          url: http://navnav.co/
        - name: Really Good UX
          description: A library of screenshots and examples of really good UX. Brought to you by
          url: https://www.reallygoodux.io/
    - name: 图标素材
      sites:
        - name: Iconfinder
          description: 2,100,000+ free and premium vector icons.
          url: https://www.iconfinder.com
        - name: iconfont
          description: 阿里巴巴矢量图标库
          url: http://www.iconfont.cn/
        - name: iconmonstr
          description: Free simple icons for your next project
          url: https://iconmonstr.com/
        - name: Icon Archive
          description: Search 590,912 free icons
          url: http://www.iconarchive.com/
        - name: FindIcons
          description: Search through 300,000 free icons
          url: https://findicons.com/
        - name: IcoMoonApp
          description: Icon Font, SVG, PDF & PNG Generator
          url: https://icomoon.io/app/
        - name: easyicon
          description: PNG、ICO、ICNS格式图标搜索、图标下载服务
          url: http://www.easyicon.net/
        - name: flaticon
          description: 634,000+ Free vector icons in SVG, PSD, PNG, EPS format or as ICON FONT.
          url: https://www.flaticon.com/
        - name: UICloud
          description: The largest user interface design database in the world.
          url: http://ui-cloud.com/
        - name: Material icons
          description: Access over 900 material system icons, available in a variety of sizes and densities, and as a web font.
          url: https://material.io/icons/
        - name: Font Awesome Icon
          description: The complete set of 675 icons in Font Awesome
          url: fontawesomeicon
        - name: ion icons
          description: The premium icon font for Ionic Framework.
          url: http://ionicons.com/
        - name: Simpleline Icons
          description: Simple line Icons pack
          url: http://simplelineicons.com/
    - name: 平面素材
      sites:
        - name: wallhalla
          description: Find awesome high quality wallpapers for desktop and mobile in one place.
          url: https://wallhalla.com/
        - name: 365PSD
          description: Free PSD & Graphics, Illustrations
          url: https://365psd.com/
        - name: Medialoot
          description: Free & Premium Design Resources — Medialoot
          url: https://medialoot.com/
        - name: 千图网
          description: 专注免费设计素材下载的网站
          url: http://www.58pic.com/
        - name: 千库网
          description: 免费png图片背景素材下载
          url: http://588ku.com/
        - name: 我图网
          description: 我图网,提供图片素材及模板下载,专注正版设计作品交易
          url: http://www.ooopic.com/
        - name: 90设计
          description: 电商设计（淘宝美工）千图免费淘宝素材库
          url: http://90sheji.com/
        - name: 昵图网
          description: 原创素材共享平台
          url: http://www.nipic.com/
        - name: 懒人图库
          description: 懒人图库专注于提供网页素材下载
          url: http://www.lanrentuku.com/
        - name: 素材搜索
          description: 设计素材搜索聚合
          url: http://so.ui001.com/
        - name: PS饭团网
          description: 不一样的设计素材库！让自己的设计与众不同！
          url: http://psefan.com/
        - name: 素材中国
          description: 免费素材共享平台
          url: http://www.sccnn.com/
        - name: freepik
          description: More than a million free vectors, PSD, photos and free icons.
          url: https://www.freepik.com/
    - name: Mockup
      sites:
        - name: MockupZone
          description: Mockup Zone is an online store where you can find free and premium PSD mockup files to show your designs in a professional way.
          url: https://mockup.zone/
        - name: Dunnnk
          description: Generate Product Mockups For Free
          url: http://dunnnk.com/
        - name: Graphberry
          description: Free design resources, Mockups, PSD web templates, Icons
          url: http://www.graphberry.com/
        - name: Threed
          description: Generate 3D Mockups right in your Browser
          url: http://threed.io/
        - name: Mockup World
          description: The best free Mockups from the Web
          url: https://free.lstore.graphics/
        - name: Lstore
          description: Exclusive mindblowing freebies for designers and developers
          url: https://free.lstore.graphics/
        - name: pixeden
          description: free web resources and graphic design templates.
          url: https://www.pixeden.com/
        - name: For Graphic TM
          description: High Quality PSD Mockups for Graphic Designers.
          url: http://forgraphictm.com/
    - name: 摄影图库
      sites:
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: visualhunt
          description: 100% Free High Quality Photos
          url: https://visualhunt.com/
        - name: librestock
          description: 65,084 high quality do-what-ever-you-want stock photos
          url: https://librestock.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
        - name: SplitShire
          description: Free Stock Photos and Videos for commercial use.
          url: https://www.splitshire.com/
        - name: StockSnap
          description: Beautiful free stock photos
          url: https://stocksnap.io/
        - name: albumarium
          description: The best place to find & share beautiful images
          url: http://albumarium.com/
        - name: myphotopack
          description: A free photo pack just for you. Every month.
          url: https://myphotopack.com/
        - name: Notaselfie
          description: Photos that happen along the way. You can use the images anyway you like. Have fun!
          url: http://notaselfie.com/
        - name: papers
          description: Wallpapers Every Hour!Hand collected :)
          url: http://papers.co/
        - name: stokpic
          description: Free Stock Photos For Commercial Use
          url: http://stokpic.com/
        - name: 55mm
          description: Use our FREE photos to tell your story!
          url: https://55mm.co/visuals
        - name: thestocks
          description: Use our FREE photos to tell your story!
          url: http://thestocks.im/
        - name: freenaturestock
          description: Exclusive mindblowing freebies for designers and developers
          url: http://freenaturestock.com/
        - name: negativespace
          description: Beautiful, High-Resolution Free Stock Photos
          url: https://negativespace.co/
        - name: gratisography
          description: Free high-resolution pictures you can use on your personal and commercial projects, free of copyright restrictions.
          url: https://gratisography.com/
        - name: imcreator
          description: A curated collection of free web design resources, all for commercial use.
          url: http://imcreator.com/free
        - name: lifeofpix
          description: Free high resolution photography
          url: http://www.lifeofpix.com/
        - name: skitterphoto
          description: Free Stock Photos for Creative Professionals
          url: https://skitterphoto.com/
        - name: mmtstock
          description: Free photos for commercial use
          url: https://mmtstock.com/
        - name: magdeleine
          description: HAND-PICKED FREE PHOTOS FOR YOUR INSPIRATION
          url: https://magdeleine.co/browse/
        - name: jeshoots
          description: New Free Photos & Mockups in to your Inbox!
          url: http://jeshoots.com/
        - name: hdwallpapers
          description: High Definition Wallpapers & Desktop Backgrounds
          url: https://www.hdwallpapers.net
        - name: publicdomainarchive
          description: New 100% Free Stock Photos. Every. Single. Week.
          url: http://publicdomainarchive.com/
    - name: PPT资源
      sites:
        - name: OfficePLUS
          description: OfficePLUS，微软Office官方在线模板网站！
          url: http://www.officeplus.cn/Template/Home.shtml
        - name: 优品PPT
          description: 高质量的模版，而且还有PPT图表，PPT背景图等资源
          url: http://www.ypppt.com/
        - name: PPT+
          description: PPT加直播、录制和分享—PPT+语音内容分享平台
          url: http://www.pptplus.cn/
        - name: PPTMind
          description: 分享高端ppt模板与keynote模板的数字作品交易平台
          url: http://www.pptmind.com/
        - name: tretars
          description: The best free Mockups from the Web
          url: http://www.tretars.com/ppt-templates
        - name: 5百丁
          description: 中国领先的PPT模板共享平台
          url: http://ppt.500d.me/
    - name: 图形创意
      sites:
        - name: photoshop
          description: Photoshop不需要解释
          url: https://www.adobe.com/cn/products/photoshop.html
        - name: Affinity Designer
          description: 专业创意软件
          url: https://affinity.serif.com/
        - name: Illustrator
          description: 矢量图形和插图。
          url: https://www.adobe.com/cn/products/illustrator/
        - name: indesign
          description: 页面设计、布局和出版。
          url: http://www.adobe.com/cn/products/indesign.html
        - name: cinema-4d
          description: Cinema 4D is the perfect package for all 3D artists who want to achieve breathtaking results fast and hassle-free.
          url: https://www.maxon.net/en/products/cinema-4d/overview/
        - name: 3ds-max
          description: 3D modeling, animation, and rendering software
          url: https://www.autodesk.com/products/3ds-max/overview
        - name: Blender
          description: Blender is the free and open source 3D creation suite.
          url: https://www.blender.org/

    - name: 在线工具
      sites:
        - name: tinypng
          description: Optimize your images with a perfect balance in quality and file size.
          url: https://tinypng.com/
        - name: goqr
          description: create QR codes for free (Logo, T-Shirt, vCard, EPS)
          url: http://goqr.me/
        - name: ezgif
          description: simple online GIF maker and toolset for basic animated GIF editing.
          url: https://ezgif.com
        - name: Android 9 patch
          description: Android 9-patch shadow generator fully customizable shadows
          url: http://inloop.github.io/shadow4android/
        - name: screen sizes
          description: Viewport Sizes and Pixel Densities for Popular Devices
          url: http://screensiz.es/
        - name: svgomg
          description: SVG在线压缩平台
          url: https://jakearchibald.github.io/svgomg/
        - name: 稿定抠图
          description: 免费在线抠图软件,图片快速换背景-抠白底图
          url: https://www.gaoding.com


