# title of website
title: webstack

# description of website
description: luckyhakcing's navigation site

# favicon of website
favicon: "https://webstack.cc/assets/images/favicon.png"

# your website url
url: https://ws.wrss.top

# github profile url
github: "https://github.com/toolsz/webstack"

# footer message
footer: © 2021-2021 @luckyhacking

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
# google_analytics: "G-EXE1PJ8CR2"

content:
  categories:
    - name: 在线IDE
      sites:
        - name: 在线golang
          description: 有代码提示, 比golang官方的playground好用
          url: https://goplay.tools/
        - name: 在线PHP
          url: https://3v4l.org/
        - name: Replit
          description: 在线使用的通用IDE, 支持所有主流语言, 但是需要登录, 比较麻烦
          url: https://replit.com/
        - name: Colaboratory
          description: 在线使用的Jupyter notebook环境, 机器学习必备
          url: https://colab.research.google.com/
        - name: Compiler Explorer
          description: 在线C++编译器能够查看c++/rust/golang编译过程的在线编译器
          url: https://godbolt.org/
          
    - name: 开发工具
      sites:
        - name: Pagespeed Insights
          description: 页面性能分析工具，很好用
          url: https://pagespeed.web.dev/
        - name: deps.dev
          description: 用来查看开源项目的依赖是否有漏洞
          url: https://deps.dev/
        - name: Staticfile CDN
          description: 收录知名开源js、css等静态资源的网站
          url: https://www.staticfile.org/
        - name: 网易DNS检测工具
          description: 
          url: http://nstool.netease.com/
        - name: Diffchecker
          description: diff 工具，diff 文本、diff 图片、diff PDF
          url: https://www.diffchecker.com/diff
        - name: misaka ping
          description:
          url: https://ping.sx/ping
        - name: Github Compare
          description: 对比多个github的repo, go.libhunt.com也支持类似功能, 但是只能比较golang的lib
          url: https://www.githubcompare.com/
        - name: ProgramCreek
          description: 一些lib的使用例子, 但是只支持java/python/c++/scala, 不知道某个lib的用法时, 可以先在这个网站查查
          url: https://www.programcreek.com/
          
          
    - name: 综合在线工具
      sites:
        - name: OKTools
          url: https://oktools.net/number
        - name: transform
          description: 各种数据类型转换
          url: https://transform.tools/
        - name: verytoolz
          description: 各种数据类型转换
          url: https://verytoolz.com/yaml-parser.html
        - name: online-xxx-tools
          description: 用来转换各种数据类型和文件格式 (用来搜yamllint工具时发现的)
          url: https://onlinecsvtools.com/
        - name: CloudConvert
          description: 在线文件转换网站，所有格式应有尽有
          url: https://cloudconvert.com/
          
    - name: 开发文档
      sites:
        - name: golang标准库
          url: https://pkg.go.dev/std
        - name: gf文档
          url: https://pkg.go.dev/github.com/gogf/gf/v2
        - name: Goland文档
          description: IDE相关问题别再乱查各种帖子了，直接看文档最好
          url: https://www.jetbrains.com/help/go/meet-the-product.html
        - name: alpine-packages
          url: https://pkgs.alpinelinux.org/packages
    - name: golang平台
      sites:
        - name: CodeCov
          description:
          url: https://about.codecov.io/
        - name: Go Report Card
          description:
          url: https://goreportcard.com/
        - name: coveralls
          description:
          url: https://coveralls.io/
    - name: 云服务文档
      sites:
        - name: API Hub
          description: apifox提供的api开放平台，提供了基本上所有主流服务的文档和调试，用起来很方便
          url: https://www.apifox.cn/apihub/
        - name: 云片
          url: https://www.yunpian.com/
        - name: 聚合数据
          url: https://www.juhe.cn/
        - name: nowapi
          description: 常用api服务,还有余额
          url: https://www.nowapi.com/
        - name: 百度智能云
          description: 百度智能云,用过车牌识别之类的服务
          url: https://cloud.baidu.com/
        - name: 高德开放平台
          description: 地图服务
          url: https://lbs.amap.com/
        - name: 超级鹰
          description: 打码平台,还不错
          url: https://www.chaojiying.com/
        - name: 腾讯防水墙
          description: 验证码/内容平台防垃圾内容等服务
          url: https://007.qq.com/
        - name: 芝麻HTTP
          descriptin: 比较好用的代理IP网站, 但是不便宜, 用过几次还可以
          url: https://h.zhimaruanjian.com/
    - name: 正则
      sites:
        - name: regex101
          description: 正则在线调试网站，非常好用
          url: https://regex101.com/
        - name: 正则大全any-rule
          description: 收录了常用业务的正则
          url: https://any86.github.io/any-rule/
        - name: 图解正则Regexper
          description: 图解正则
          url: https://regexper.com/
    - name: 日常服务
      sites:
        - name: Markmap
          description: 在线markdown转思维导图
          url: https://markmap.js.org/repl
        - name: Mermaid Live Editor
          description: 在线mermaid编辑器
          url: https://mermaid.live/edit/
        - name: Excalidraw
          description: 流程图工具，可以画手写风格的图表
          url: https://excalidraw.com/
        - name: OpenSource Builders
          description: 一些服务的开源替代品，还不错
          url: https://opensource.builders/
        - name: 逮蝦戶
          description: spotify之类境外服务的拼车网站
          url: https://daixiahu.co/#/buses
        - name: xclient
          description: mac的破解软件
          url: https://xclient.info/
        - name: Table Convert
          description: tableconvert
          url: https://tableconvert.com/
        - name: 云短信
          description: 在线短信接收平台,用来注册临时使用(只使用一次)的网站
          url: https://yunduanxin.net/
        - name: iLovePDF
          description: 提供所有PDF相关的在线服务
          url: https://www.ilovepdf.com/
        - name: 白描OCR
          description: 白描OCR的在线服务
          url: https://web.baimiaoapp.com/
        - name: 在线markdown编辑器
          description: 比StackEdit好用很多，用来辅助处理一些md格式问题
          url: https://md.mzr.me/
        - name: TinyPNG
          description: 在线图片压缩服务
          url: https://tinypng.com/
        - name: IPLC
          description: 翻墙工具
          url: https://portal.uuks.club/
#         - name: IconFont
#           description: 阿里巴巴矢量图标库
#           url: http://www.iconfont.cn/
        - name: EasyIcon
          description: PNG、ICO、ICNS格式图标搜索、图标下载服务
          url: http://www.easyicon.cc/
        - name: FlatIcon
          description: 类似EasyIcon, 可以直接搜索icon
          url: https://www.flaticon.com/
#         - name: 稿定抠图
#           description: 免费在线抠图软件,图片快速换背景-抠白底图
#           url: https://www.gaoding.com
        - name: 草料二维码
          description: 
          url: https://cli.im/
        - name: Blogtrottr
          description: 订阅rss, 发送到邮箱(ttrss也支持发送某个feed到邮箱的功能)
          url: https://blogtrottr.com/
        - name: 蜜蜂剪辑
          description: 蜜蜂剪辑，在线音视频处理
          url: https://beecut.cn/
        - name: Zamzar
          description:  视频/音频/图片/电子书转换器, 非常强大的在线工具
          url: https://www.zamzar.com/
        - name: Google翻译
          description: 
          url: https://translate.google.cn/?sl=auto&tl=en&op=translate
        - name: ChartCube
          description: 相当于可以在线使用的echarts, 可以导出饼图柱状图折线图等, 但仅支持导入csv/excel/json数据
          url: https://chartcube.alipay.com/upload
        - name: 冷熊简历
          description: 用来生成简历pdf文件, 很不错
          url: https://cv.ftqq.com/#
        - name: 开源服务的badage服务
          description: 提供了很多常用badage, 比如license/发布版本/下载量/文档/last-commit时间, 还可以定制徽章, 比如qq群/捐赠地址等;
          url: https://shields.io/
        - name: httpbin
          description: 用来通过查看url请求是否符合预期, 来看代码是否有问题, 或者当前网络环境(比如容器内)是否有问题
          url: http://httpbin.org/
    - name: 投资
      sites:
        - name: Investment Calculator
          description: 计算投资收益什么的，好用
          url: https://www.calculator.net/investment-calculator.html
        - name: 烯牛数据
          description: 免费的投创数据平台，其他类似的都要收费
          url: https://www.xiniudata.com/
        - name: Neat Reader
          description: 在线阅读ePUB/mobi等格式文件, 阅读体验不错, 不再需要下载calibre之类的本地阅读器
          url: https://www.neat-reader.cn/
        - name: Kaggle
          description: 数据挖掘的比赛网站
          url: https://www.kaggle.com/
        - name: JoinQuant聚宽量化交易平台
          description: 相当于国内的Kaggle, 没事下载几个策略跑跑
          url: https://www.joinquant.com/

          
          
#     - name: chrome拓展/弃用备份
#       sites:
#         - name: Tamper Chrome
#           description: 类似burp suite的工具, 修改请求
#           url: https://chrome.google.com/webstore/detail/tamper-chrome-extension/hifhgpdkfodlpnlmlnmhchnkepplebkb
#         - name: loom
#           description: chrome的录屏插件
#           url: https://chrome.google.com/webstore/detail/loom-%E2%80%93-free-screen-and-ca/liecbddmkiiihnedobmlmillhodjkdmb
#         - name: hqweay/bookmark-tools
#           description: mac上chrome书签文件夹转markdown
#           url: https://github.com/hqweay/bookmark-tools
#         - name: moonD4rk/HackBrowserData
#           description: 导出浏览器数据的工具
#           url: https://github.com/moonD4rk/HackBrowserData
#         - name: 音乐解锁
#           description: 把网易云音乐、QQ音乐等软件的专用音频格式转为MP3
#           url: https://chrome.google.com/webstore/detail/%E9%9F%B3%E4%B9%90%E8%A7%A3%E9%94%81/gldlhhhmienbhlpkfanjpmffdjblmegd
#         - name: Enhanced GitHub
#           description: 对gitzip的补充, 实际上用处不大, 只能查看文件大小(无法查看文件夹); 但是严重延迟网页加载, 所以卸载;
#           url: https://chrome.google.com/webstore/detail/enhanced-github/anlikcnbgdeidpacdbdljnabclhahhmd
#         - name: Star History
#           description: 查看repo的star历史, 用来对比repo, 查看repo活跃度以及是否刷star
#           url: https://chrome.google.com/webstore/detail/star-history/iijibbcdddbhokfepbblglfgdglnccfn
#         - name: JetBrains Toolbox Extension
#           description: 用来直接在jb家IDE中打开repo, 需要搭配Toolbox的APP使用, 还行但没必要
#           url: https://chrome.google.com/webstore/detail/jetbrains-toolbox-extensi/offnedcbhjldheanlbojaefbfbllddna
