# title of website
title: webstack

# description of website
description: luckyhakcing's navigation site

# favicon of website
favicon: "https://webstack.cc/assets/images/favicon.png"

# your website url
url: https://ws.wrss.top

# github profile url
github: "https://github.com/toolsz/webstack"

# footer message
footer: © 2021-2021 @luckyhacking

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
# google_analytics: "G-EXE1PJ8CR2"

content:
  categories:
    - name: 常用网站
      sites:
        - name: alist
          url: https://alist.wrss.top/aliyundrive
        - name: mali
          url: https://mali.wrss.top/
        - name: ttrss
          url: https://ttrss.wrss.top/
        - name: 阿里云盘
          url: https://www.aliyundrive.com/drive
        - name: teambition
          url: https://www.teambition.com/project/5e703a1ffb67050022013213/tasks
        - name: linear
          url: https://linear.app/
        - name: github
          url: https://github.com/luckyhacking
        - name: 即时工具67tool
          url: https://www.67tool.com/
        - name: 一个工具箱atoolbox
          description: 使用其图片拼接功能
          url: http://www.atoolbox.net/Tool.php?Id=978
        - name: Google翻译 - translate
          url: https://translate.google.cn/?sl=auto&tl=en&op=translate



    - name: 开发工具
      sites:
        - name: Replit
          description: 在线使用的通用IDE，支持所有主流语言（完美替代其他在线IDE）
          url: https://replit.com/
        - name: Pagespeed Insights
          description: 页面性能分析工具，很好用
          url: https://pagespeed.web.dev/
        - name: devtool.tech
          url: https://devtool.tech/

        - name: itdog
          url: https://www.itdog.cn/
        - name: webutils
          description: 提供在线curl工具，以及一些文本和图片工具
          url: https://www.webutils.app/

# github相关
        - name: deps.dev
          description: 用来查看开源项目的依赖是否有漏洞
          url: https://deps.dev/
        - name: Github Compare
          description: 对比多个github的repo，go.libhunt.com也支持类似功能，但是只能比较golang的lib
          url: https://www.githubcompare.com/
        - name: Github Star Charts
          description: 比GitHub Star History好用
          url: https://starchart.cc/
        - name: Github OSS Insight
          description: xxx
          url: https://ossinsight.io/
        - name: Github active-forks
          description: 查找repo最活跃的fork
          url: https://techgaun.github.io/active-forks/index.html


        - name: 网易DNS检测工具
          url: http://nstool.netease.com/
        - name: misaka ping
          url: https://ping.sx/ping
        - name: DNSdumpster
          description: 查看某个域名下的所有二级域名
          url: https://dnsdumpster.com/
          
        - name: Staticfile CDN
          description: 收录知名开源js、css等静态资源的网站
          url: https://www.staticfile.org/
        - name: Diffchecker
          description: diff 工具，diff 文本、diff 图片、diff
          url: https://www.diffchecker.com/diff

        - name: Program Creek
          description: 一些lib的使用例子，但是只支持java/python/c++/scala，不知道某个lib的用法时，可以先在这个网站查查
          url: https://www.programcreek.com/
        - name: 阿里云镜像源
          url: https://developer.aliyun.com/mirror/
        - name: 中科大镜像源
          url: https://mirrors.ustc.edu.cn/
        - name: 数据结构模拟 Data Structure Visualizations
          description: 各种数据结构的动画
          url: https://www.cs.usfca.edu/~galles/visualization/Algorithms.html

        - name: httpbin
          description: 用来通过查看url请求是否符合预期，来看代码是否有问题，或者当前网络环境（比如容器内）是否有问题
          url: http://httpbin.org/
          
# 正则相关
        - name: regex101
          description: 正则在线调试网站，非常好用
          url: https://regex101.com/
        - name: 正则大全any-rule
          description: 收录了常用业务的正则
          url: https://any86.github.io/any-rule/
        - name: iHateRegex
          description: 收录了更多的常用正则
          url: https://ihateregex.io/
        - name: 图解正则regex-vis
          description: 比Regexper好用
          url: https://regex-vis.com/
        - name: regexlearn
          description: regex游乐场
          url: https://regexlearn.com/zh-cn/learn

        - name: Crontab.guru
          url: https://crontab.guru/
          
          
        - name: paperswithcode
          description: 论文+代码（ML相关）
          url: https://paperswithcode.com/
        - name: readme.so
          description: 辅助写README的工具，还不错
          url: https://readme.so/editor
        - name: favicon.io
          description: 生成icon
          url: https://favicon.io/

#         - name: 在线golang
#           description: 有代码提示，比golang官方的playground好用
#           url: https://goplay.tools/
#         - name: 在线PHP
#           url: https://3v4l.org/
#         - name: Colaboratory
#           description: 在线使用的Jupyter notebook环境，机器学习必备
#           url: https://colab.research.google.com/
#         - name: Compiler Explorer
#           description: 在线C++编译器能够查看c++/rust/golang编译过程的在线编译器
#           url: https://godbolt.org/
#         - name: Nginx Config
#           description: 用来生成nginx配置文件
#           url: https://www.digitalocean.com/community/tools/nginx?global.app.lang=zhCN


          
          
# 转换工具
        - name: OKTools
          url: https://oktools.net/number
        - name: transform
          description: 各种数据类型转换
          url: https://transform.tools/
        - name: verytoolz
          description: 各种数据类型转换
          url: https://verytoolz.com/yaml-parser.html
        - name: online-xxx-tools
          description: 用来转换各种数据类型和文件格式 (用来搜yamllint工具时发现的)
          url: https://onlinecsvtools.com/


# 平台
        - name: CodeCov
          url: https://about.codecov.io/
        - name: Go Report Card
          url: https://goreportcard.com/
        - name: coveralls
          url: https://coveralls.io/
          

          
    - name: 开发文档
      sites:
        - name: golang标准库
          url: https://pkg.go.dev/std
        - name: gf文档
          url: https://pkg.go.dev/github.com/gogf/gf/v2
        - name: go-zero文档
          url: https://go-zero.dev/cn/docs/introduction/
        - name: Goland文档
          description: IDE相关问题别再乱查各种帖子了，直接看文档最好
          url: https://www.jetbrains.com/help/go/meet-the-product.html
        - name: alpine-packages
          url: https://pkgs.alpinelinux.org/packages
        - name: GORM文档
          url: https://gorm.io/zh_CN/docs/index.html
        - name: pre-commit的hooks和文档
          description: 提供的所有hooks，也可以看看文档
          url: https://pre-commit.com/hooks.html
        - name: Docker文档
          description: 文档写的特别好，三个部分：docker命令/Dockerfile/docker-compose
          url: https://docs.docker.com/engine/reference/run/

        - name: Prometheus文档
          url: https://prometheus.io/docs/prometheus/latest/getting_started/
        - name: Redis命令/文档
          description: 主要用来查命令（当然，还有文档）
          url: https://redis.io/commands/
        - name: Gitea文档
          url: https://docs.gitea.io/zh-cn/
        - name: UmiJS文档
          url: https://umijs.org/zh-CN/docs/load-on-demand
        - name: casbin文档
          url: https://casbin.org/docs/zh-CN/overview
        - name: Ansible文档
          description: 找了几个中文版文档，版本都很老（将就看英文版吧）
          url: https://docs.ansible.com/ansible/latest/index.html
        - name: Ansible Galaxy
          url: https://galaxy.ansible.com/home
        - name: Element文档
          description: ⚠️注意版本
          url: https://element.faas.ele.me/2.14/#/zh-CN/component/layout
        - name: Element Plus文档
          url: https://element-plus.gitee.io/zh-CN/component/button.html
 
        - name: k8s文档
          url: https://kubernetes.io/zh/docs/reference/
        - name: kubesphere
          url: https://kubesphere.io/zh/
        - name: Artifact Hub
          url: https://artifacthub.io/packages/search?sort=relevance&page=1
        - name: Helm
          url: https://helm.sh/zh/docs/intro/quickstart/
        - name: 云原生资料库
          description: k8s/Istio/Envoy教程
          url: https://lib.jimmysong.io/kubernetes-handbook/


        - name: LeetCode
          url: https://leetcode-cn.com/
        - name: CodeTop企业题库
          url: https://codetop.cc/home
        - name: gh-actions集合
          url: https://github.com/marketplace?type=actions
        - name: gh-actions官方文档
          url: https://docs.github.com/cn/actions/quickstart
        - name: gitlab官方文档
          url: https://docs.gitlab.com/ee/
          
        - name: AWESOME-LIST
          url: https://asmcn.icopy.site/awesome/awesome-zsh-plugins/
          
          
          

    - name: 云服务文档
      sites:
        - name: API Hub
          description: apifox提供的api开放平台，提供了基本上所有主流服务的文档和调试，用起来很方便
          url: https://www.apifox.cn/apihub/
        - name: 云片
          url: https://www.yunpian.com/
        - name: 聚合数据
          url: https://www.juhe.cn/
#         - name: nowapi
#           description: 常用api服务（还有余额）但是这网站实在没什么好用的API服务了，所以暂时去掉。
#           url: https://www.nowapi.com/
        - name: 百度智能云
          description: 百度智能云，用过车牌识别之类的服务
          url: https://cloud.baidu.com/
        - name: 高德开放平台
          url: https://lbs.amap.com/
        - name: 超级鹰
          description: 打码平台，还不错
          url: https://www.chaojiying.com/
        - name: 腾讯防水墙
          description: 验证码/内容平台防垃圾内容等服务
          url: https://007.qq.com/
        - name: 芝麻HTTP
          descriptin: 比较好用的代理IP网站，但是不便宜，用过几次还可以
          url: https://h.zhimaruanjian.com/
 
          
    - name: web3
      sites:
        - name: Seed Club
          url: https://www.seedclub.xyz/
        - name: Mirror
          url: https://mirror.xyz/
        - name: UNISWAP
          url: https://uniswap.org/
        - name: FWB
          url: https://www.fwb.help/
        - name: Bankless DAO
          url: https://www.bankless.community/
        - name: DAOrayaki
          url: https://media.daorayaki.org/
        - name: cryptofonts
          description: 加密货币的icon
          url: https://cryptofonts.com/icons.php
          
          
          


    - name: 日常生活
      sites:
        - name: OpenSource Builders
          description: 一些服务的开源替代品，还不错
          url: https://opensource.builders/
        - name: 白描OCR
          description: 白描OCR的在线服务
          url: https://web.baimiaoapp.com/
        - name: 草料二维码
          url: https://cli.im/
        - name: qrcode-monkey
          description: 搭配草料使用（主要使用其一些国外服务的logo）
          url: https://www.qrcode-monkey.com/
        - name: 在线尺子achizi
          url: http://achizi.com/
          
# 天气
        - name: 墨迹天气
          url: https://tianqi.moji.com/
        - name: Weather Spark
          description: 全年气候和平均天气
          url: https://zh.weatherspark.com/y/137446/%E4%B8%AD%E5%9B%BD%E3%80%81%E4%B8%8A%E6%B5%B7%E5%B8%82%E7%9A%84%E5%85%A8%E5%B9%B4%E5%B9%B3%E5%9D%87%E5%A4%A9%E6%B0%94
#         - name: ventusky
#           description: 其实没什么用，还不如墨迹
#           url: https://www.ventusky.com/?p=31.2;121.5;5&l=temperature-2m

# 文档相关
        - name: 木及简历
          url: https://www.mujicv.com/editor/?id=template-c124a10e0db5e4b9
        - name: 冷熊简历
          url: https://cv.ftqq.com/#
        - name: Neat Reader
          description: 在线阅读ePUB/mobi等格式文件，阅读体验不错，不再需要下载calibre之类的本地阅读器
          url: https://www.neat-reader.cn/webapp#/
        - name: Koodo Reader
          url: https://reader.960960.xyz/
        - name: 写作猫
          url: https://xiezuocat.com/#/
        - name: Table Convert
          url: https://tableconvert.com/
          
          

        - name: IPLC
          url: https://portal.uuks.club/
        - name: telegram
          url: https://web.telegram.im/
        - name: 微软邮箱Outlook
          url: https://outlook.live.com/



        - name: 油猴脚本Greasy Fork
          url: https://greasyfork.org/zh-CN
        - name: SPEEDTEST
          url: https://www.speedtest.net/zh-Hans
#         - name: 逮蝦戶
#           description: spotify之类境外服务的拼车网站
#           url: https://daixiahu.co/#/buses
#         - name: xclient
#           description: mac的破解软件
#           url: https://xclient.info/
#         - name: 云短信
#           description: 在线短信接收平台，用来注册临时使用(只使用一次)的网站
#           url: https://yunduanxin.net/
#         - name: 蜜蜂剪辑
#           description: 蜜蜂剪辑，在线音视频处理
#           url: https://beecut.cn/
#         - name: 好工具周刊BestXTools
#           url: https://discuss-cn.bestxtools.com/
#         - name: 中文播客榜
#           url: https://xyzrank.com/

          
# icon相关
        - name: EasyIcon
          description: PNG、ICO、ICNS格式图标搜索、图标下载服务
          url: http://www.easyicon.cc/
        - name: FlatIcon
          description: 类似EasyIcon，可以直接搜索icon
          url: https://www.flaticon.com/
#         - name: IconFont
#           description: 阿里巴巴矢量图标库
#           url: http://www.iconfont.cn/




# rss相关服务
        - name: feeddd
          description: 订阅微信公众号的feed（可以代替werss，werss服务不太稳）
          url: https://feeddd.org/feeds
        - name: Kill the Newsletter!
          description: newsletter转rss
          url: https://kill-the-newsletter.com/
        - name: follow.it
          description: rss转newsletter
          url: https://follow.it/enter-website
#         - name: Blogtrottr
#           description: 订阅rss，发送到邮箱(ttrss内置“发送某个feed到邮箱”功能，所以不需要)
#           url: https://blogtrottr.com/


# 工具集网站
        - name: 偷懒工具toolight
          description: 使用其密码生成器等工具
          url: https://toolight.cn/
        - name: Cloud Convert
          description: 在线文件转换网站，所有格式应有尽有（比Zamzar支持更多格式）
          url: https://cloudconvert.com/
        - name: iLovePDF
          description: 提供所有PDF相关的在线服务
          url: https://www.ilovepdf.com/
#         - name: Zamzar
#           description: 视频/音频/图片/电子书转换器，非常强大的在线工具
#           url: https://www.zamzar.com/
#         - name: password-generator
#           description: 密码生成器
#           url: https://mrjooz.github.io/password-generator


# 图片相关服务
        - name: iLoveIMG
          description: 使用其图片压缩/图片编辑/修改图片分辨率/图片格式转换等功能
          url: https://www.iloveimg.com/zh-cn

#         - name: tldraw
#           description: 画板工具，挺好用，导出格式tldr（可以用来拼接图片，搭配iLoveIMG使用）
#           url: https://www.tldraw.com/
#         - name: TinyPNG
#           description: 在线图片压缩服务（picdiet/yalijuda）
#           url: https://tinypng.com/
#         - name: Free Image Resizer
#           description: 修改图片分辨率，非常实用
#           url: https://promo.com/tools/image-resizer/
#         - name: 稿定抠图
#           description: 免费在线抠图软件，图片快速换背景-抠白底图
#           url: https://www.gaoding.com


# 投资相关服务
        - name: Investment Calculator
          description: 计算投资收益什么的，好用
          url: https://www.calculator.net/investment-calculator.html
        - name: 烯牛数据
          description: 免费的投创数据平台，其他类似的都要收费
          url: https://www.xiniudata.com/
        - name: Kaggle
          description: 数据挖掘的比赛网站
          url: https://www.kaggle.com/
        - name: JoinQuant聚宽量化交易平台
          description: 相当于国内的Kaggle，没事下载几个策略跑跑
          url: https://www.joinquant.com/
        - name: 七麦数据
          url: https://www.qimai.cn/

        - name: Graph Maker
          url: https://linegraphmaker.co/bar-graph
#         - name: ChartCube
#           description: 相当于可以在线使用的echarts，可以导出饼图柱状图折线图等，但仅支持导入csv/excel/json数据
#           url: https://chartcube.alipay.com/upload

        - name: wikihow
          url: https://zh.wikihow.com/%E9%A6%96%E9%A1%B5



# 文档工具
#         - name: Markmap
#           description: 在线markdown转思维导图
#           url: https://markmap.js.org/repl
#         - name: Mermaid Live Editor
#           description: 在线mermaid编辑器
#           url: https://mermaid.live/edit/
#         - name: Excalidraw
#           description: 流程图工具，可以画手写风格的图表
#           url: https://excalidraw.com/
#         - name: 在线markdown编辑器
#           description: 比StackEdit好用很多，用来辅助处理一些md格式问题
#           url: https://md.mzr.me/



#         - name: WakaTime
#           description: 用来通过IDE插件统计项目，便于回溯，以及写周报什么的
#           url: https://wakatime.com/dashboard

#         - name: 开源服务的badage服务
#           description: 提供了很多常用badage，比如license/发布版本/下载量/文档/last-commit时间，还可以定制徽章，比如qq群/捐赠地址等
#           url: https://shields.io/
#         - name: 硬创社
#           url: https://x.jlc.com/
#         - name: 设计工具排行uxtools
#           url: https://uxtools.co/tools/design
#         - name: 隔离食用手册
#           url: https://cook.yunyoujun.cn/
#         - name: SOU.BEST
#           url: https://sou.best/





    - name: 购物
      sites:
        - name: 国标/行标
          description: 查看全文，自带搜索功能，输入关键字或者国标编号即可
          url: http://openstd.samr.gov.cn/bzgk/gb/std_list
        - name: ProductZ
          url: https://productz.com/en
        - name: IKEA
          url: https://www.ikea.cn/cn/zh/cat/chu-wu-he-shou-na-st001/
        - name: MUJI
          url: https://www.muji.com.cn/cn/store/
        - name: REI
          url: https://www.rei.com/
        - name: 充电头网手机充电兼容性测试数据库
          url: https://shimo.im/sheets/aBAYV0nY69S90V3j

#         - name: Top10Zone
#           description: 几个缺点：商品种类太少，且很多Top10商品实际上一般（并且没有很多很好用的国内品牌），另外更新很慢，大部分榜单还是2020年的
#           url: https://www.top10-zone.com/
#         - name: 始祖鸟
#           url: https://arcteryx.com/ca/zh/c/mens
#         - name: 始祖鸟leaf
#           url: https://leaf.arcteryx.com/ca/en/c/combat-uniforms







